### ISSUE TITLE
Always indent @​example code​

### ISSUE THREAD

**Issue by FWeinb** [SassDoc/sassdoc.github.io#102]
I think we should recommend to always indent [@​example](http://sassdoc.com/develop/annotations/#example) code because it can have some problems when encountering `@include/@function`.

SassDoc/sassdoc#328

**Comment by valeriangalliat** [comment]
:+1:

**Comment by HugoGiraudel** [comment]
RFR: https://github.com/SassDoc/sassdoc.github.io/pull/103.
