### ISSUE TITLE
Document `exclude` configuration key

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sassdoc.github.io#105]
https://github.com/SassDoc/sassdoc/blob/develop/src/sassdoc.js#L268
https://github.com/SassDoc/sassdoc/blob/develop/src/exclude.js

**Comment by HugoGiraudel** [comment]
Who takes it?

**Comment by pascalduez** [comment]
I could take it after the coverage thing, but would gladly delegate :-)
There's tests for it now: https://github.com/SassDoc/sassdoc/blob/develop/test/api/exclude.test.js
