### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by filtercake** [SassDoc/sassdoc.github.io#112]
noticed this:

![image](https://cloud.githubusercontent.com/assets/170145/6167297/36243e28-b2ba-11e4-85f2-969f46a65e78.png)

left is chrome, right is safari

**Comment by HugoGiraudel** [comment]
That is very weird. Any idea why perhaps?

**Comment by filtercake** [comment]
will have a look later

**Comment by HugoGiraudel** [comment]
Alright.

**Comment by pascalduez** [comment]
Also we are hard-linking the Twitter avatars. As soon as a user change avatar the hash change.

**Comment by pascalduez** [comment]
@filtercake do you have some kind of adblocker, social shit filtering plugins in your chrome maybe ? :-)

**Comment by filtercake** [comment]
@pascalduez yes, this is chrome after disabling [Disconnect](https://disconnect.me/):

![image](https://cloud.githubusercontent.com/assets/170145/6184533/24f31e18-b363-11e4-8881-18680fdb22d2.png)

I will try to send a PR later

**Comment by valeriangalliat** [comment]
I think this issue can be closed since #114 is closed with 3531aaa42a8374925064b6de19e28d704eeee4fa.
