### ISSUE TITLE
Implement new branding

### ISSUE THREAD

**Issue by HugoGiraudel** [SassDoc/sassdoc.github.io#47]
Includes:

* [x] New logo;
* [x] An illustration;
* [x] New home page;
* [x] Partial redesign of the docs (to go with the new home);
* [x] New "Brand guidelines" page (#62);
* [x] Updates in "About" page (#4).

Design by @whyalix, code by myself.

**Comment by HugoGiraudel** [comment]
Regarding the logo, I think we are heading in the right direction. Here are the latest version from @kaishin. I do like the right version.

![Logo](https://s3-us-west-2.amazonaws.com/s.cdpn.io/2037/screenshot-2015-01-17.png)

Opinions?

**Comment by valeriangalliat** [comment]
I like the right version too.

Though I'm not sure about the `sass` font, even if it's already fine enough for me right now.

**Comment by pascalduez** [comment]
It's starting to looks pretty cool. Thanks @kaishin !
I'm fine with both versions. Although I like the script version, the right one might be more readable.

I'm wondering whether the Sass propaganda squad might grind over the lack of Cap on the first "s" ;-)

The purple/pink color sheme is great.

**Comment by FWeinb** [comment]
I like the right one too!

**Comment by HugoGiraudel** [comment]
Alright. Let's validate the right one. Now, we only need an inline version to get done with the logo (ping @kaishin).

**Comment by HugoGiraudel** [comment]
@kaishin When you have a chance, could you send over the SVG version? No rush man. :)

**Comment by kaishin** [comment]
Will do that before next week, @HugoGiraudel.

**Comment by HugoGiraudel** [comment]
No problem my friend. :)

**Comment by kaishin** [comment]
Here is a finalized Proxima Nova version (right one above) with both horizontal and vertical versions: https://dl.dropboxusercontent.com/u/148921/SassDoc%20Logo.svg

**Comment by HugoGiraudel** [comment]
Terrific Reda, I'll update the site shortly. :)

**Comment by HugoGiraudel** [comment]
Alright, PR pending: #106. We only need @whyalix to update the illustration to be alright.
