### ISSUE TITLE
Where to put migration scripts for 2.0?

### ISSUE THREAD

**Issue by valeriangalliat** [SassDoc/sassdoc.github.io#80]
In SassDoc/sassdoc#303, we have a breaking change that users can easily adapt to by using a shell script.

The question is, where does it makes sense to put this? The users needs to be aware of it because it will save them time when migrating… maybe we even need to put a warning in SassDoc itself like we did for `.sassdocrc`?

* [ ] Include [the migration script](https://github.com/SassDoc/sassdoc/issues/303#issuecomment-68525038) somewhere.

**Comment by valeriangalliat** [comment]
We could add an `UPGRADE-2.0.md` file to `sassdoc` tree, like they do for [Symfony](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md).

**Comment by HugoGiraudel** [comment]
sl

**Comment by valeriangalliat** [comment]
45fc3d2da4e6277ddcd87d0f02a67838f2e272cb
https://github.com/SassDoc/sassdoc/blob/develop/UPGRADE-2.0.md
