### ISSUE TITLE
Add a warning about --dest ./

### ISSUE THREAD

**Issue by HugoGiraudel** [SassDoc/sassdoc.github.io#81]

**Comment by valeriangalliat** [comment]
This is prohibited by safe-wipe (if `./` is effectively a parent of `src` dir).

**Comment by valeriangalliat** [comment]
So basically:

* `sassdoc scss --dest ./` will fail, thanks to safe-wipe.
* `sassdoc 'scss/**/*.scss' '!scss/foo/bar.scss' --dest ./ will fail too (glob2base can handle an array of patterns).
* `sassdoc --dest ./ < foo.scss` will fail thanks to `fs.rmdir` which won't allow to remove `./` throwing an `EINVAL` error.

So I think there's no need for a warning.
