### ISSUE TITLE
Add a page about Sassdocify

### ISSUE THREAD

**Issue by HugoGiraudel** [SassDoc/sassdoc.github.io#91]

**Comment by valeriangalliat** [comment]
sassdocify's man page is mentioned in 628e3beefbcf23cfd4b758820ef79765b251a606, not sure we need a dedicated page.

**Comment by HugoGiraudel** [comment]
We do. This is likely to be the most common usage for SassDoc. We need an extensive documentation about this to avoid what happened with @lunelson on Sass-Maps-Plus.

**Comment by valeriangalliat** [comment]
Then tell me what I need to add to http://sassdoc.com/sassdocify/. I don't want to add meaningfull information in SassDoc website that wouldn't be in the man page too.

**Comment by HugoGiraudel** [comment]
https://github.com/SassDoc/sassdoc.github.io/commit/bf69eafbd97c29231f4712b12002b840cf2ff82d.
