### ISSUE TITLE
Communicate on 2.0 beta testing

### ISSUE THREAD

**Issue by valeriangalliat** [SassDoc/sassdoc.github.io#92]
Currently 2.0 has only been Twitted a couple of times, but there's no communication about it on [sassdoc.com].

I believe 2.0 begins to be stable enough so we can push users to try it in a more official way; by mentioning it on the website, with proper installation instructions, full changelog, upgrading guide.

What I'm proposing:

* [x] Mention 2.0 on current [sassdoc.com] (in the left menu for example).
* [x] On [/develop/], add `@beta` in the npm installation command (only on [/develop/] version).
* [x] Also mention npm 2.0 is needed and can be installed with `npm install -g npm@latest` (on actual [develop branch]).
* [x] Make the changelog and upgrading instructions easy to find (on [develop branch], because they'll also be needed the few weeks after the actual 2.0 launch).
  * [x] Link to [/develop/changelog/] directly on the homepage.
  * [x] Add an upgrading page on the website like for the changelog, and link it on the homepage.

[sassdoc.com]: http://sassdoc.com/
[/develop/]: http://sassdoc.com/develop/
[/develop/changelog/]: http://sassdoc.com/develop/changelog/
[develop branch]: https://github.com/SassDoc/sassdoc.github.io/tree/develop

**Comment by pascalduez** [comment]
Looks like a good plan.

**Comment by valeriangalliat** [comment]
Waiting for @SassDoc/owners review before linking on main website.

**Comment by FWeinb** [comment]
Like it :+1: good work!

**Comment by pascalduez** [comment]
Looks all good !
:clap:

**Comment by valeriangalliat** [comment]
BTW what to so with the "Tweet it" button on homepage in /develop/? Let the default link be sassdoc.com, or make a beta-specific tweet with the develop version?
