### ISSUE TITLE
CTA on homepage

### ISSUE THREAD

**Issue by valeriangalliat** [SassDoc/sassdoc.github.io#93]
<sup>Yeah I sometime speak like a webmarketing guy.</sup>

In the 2.0 homepage, when we scroll until the bottom, the only link we have is "All these projects are documented with SassDoc" linking to the Gallery page.

It would be nice to have a nice "call to action" in the bottom, linking to the Getting Started page, because:

* we want to increase our conversion rate :trollface: 
* I'm actually quite frustrated everytime when I have to scroll up the whole page again to have the Getting Started link.

**Comment by valeriangalliat** [comment]
BTW it could be just a link on "What are you waiting for to make your own?", but a nice big yellow button under this sentence would probably be more obvious.

**Comment by HugoGiraudel** [comment]
Fair point. I'll do it.
