### ISSUE TITLE
Update all examples with inline comments

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sassdoc.github.io#96]
Following of SassDoc/sassdoc#326

Whatever the decision will be, it would be better to promote inline instead of CDoc in the official docs.

**Comment by valeriangalliat** [comment]
:+1:

**Comment by HugoGiraudel** [comment]
https://github.com/SassDoc/develop/pull/1

I'll let @valeriangalliat backport it here.

**Comment by valeriangalliat** [comment]
https://github.com/SassDoc/sassdoc.github.io/pull/97

**Comment by valeriangalliat** [comment]
Updated http://sassdoc.com/develop/.
