### ISSUE TITLE
Add Vulcan to Gallery

### ISSUE THREAD

**Issue by HugoGiraudel** [SassDoc/sassdoc.github.io#98]
http://vulcan-framework.github.io/core/

**Comment by pascalduez** [comment]
I added it this morning ?

**Comment by HugoGiraudel** [comment]
My bad.

**Comment by HugoGiraudel** [comment]
Screenshot looks odd.

**Comment by pascalduez** [comment]
Yeah add to do it manually. The automated thing was not working.
